### ISSUE TITLE
Update all doesn’t update all

### ISSUE THREAD

**Issue by aral** [elementary/settings-daemon#102]
### What Happened?

Update all did not update all.

### Steps to Reproduce

These are the steps I took. It probably won’t be easy to reproduce but documenting here so we can keep an eye out for it.

I had a bunch of operating system updates (~145) as well as app updates.

1. I hit update all
2. A bunch of updates got installed

At the end, I still had operating system updates (~125) and some app updates (of the apps that were previously listed)

### Expected Behavior

Update all should update all apps and there shouldn’t be any other updates shown once it’s complete.

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

### Log Output

```shell
n/a
```

### Hardware Info

```
OS: elementary OS 6 Odin x86_64 
Host: LabTop Mk IV 
Kernel: 5.11.0-34-generic 
Uptime: 8 days, 21 hours, 27 mins 
Packages: 2351 (dpkg), 64 (flatpak) 
Shell: fish 3.3.1 
Resolution: 3840x2160 
DE: Pantheon 
WM: Mutter(Gala) 
Terminal: io.elementary.t 
CPU: Intel i7-10710U (12) @ 4.700GHz 
GPU: Intel Device 9bca 
Memory: 7306MiB / 15875MiB 
```

**Comment by leolost2605** [comment]
This should be fixed with the move to settings-daemon 🤞
