### ISSUE TITLE
Urges users to restart before the update is complete

### ISSUE THREAD

**Issue by kdwk** [elementary/settings-daemon#103]
## What Happened

AppCenter urges users to restart before the update is complete. This can lead to updates being rudely interrupted. 

## Expected Behavior

AppCenter should wait until the update is finished before urging users to restart

## Steps to Reproduce

1. Install an update that requires restart
2. Observe the problem
3.

## Platform Information

elementary OS 6 Odin stable

**Comment by leolost2605** [comment]
This should be fixed with the move to settings-daemon because we don't have any flatpak apps updating that could confuse users anymore.
