### ISSUE TITLE
Keyboard Setting not showing

### ISSUE THREAD

**Issue by FillyAgioro** [elementary/settings-daemon#18]
## What Happened
I can't see the keyboard shortcut setting
![Screenshot](https://user-images.githubusercontent.com/50282743/97523531-917d6580-19c8-11eb-86bc-18294864fbe0.png)

Even keyboard setting in language and region setting is not opening.
![Screen record](https://user-images.githubusercontent.com/50282743/97524506-ddc9a500-19ca-11eb-9860-817a7a7698e1.gif)

## Expected Behavior
![Keyboard Setting](https://user-images.githubusercontent.com/50282743/97523464-6a269880-19c8-11eb-8d5a-a6fbc1db2993.png)

## Steps to Reproduce

1.
2.
3.

## Platform Information

elementary OS 5.1.7 Hera

**Comment by FillyAgioro** [comment]
Can anyone help me please 😞️

**Comment by jeremypw** [comment]
@FillyAgioro Firstly could you check that the package `switchboard-plug-keyboard` is installed.  Try uninstalling and reinstalling it. If that does not fix it, close the System Settings window (if it is open), then try running the command `io.elementary.switchboard` from the terminal and post any error messages produced here.

It would help if you could provide information about what version of elementary you are running and on what hardware e.g. by posting a screenshot of the "About" switchboard plug. Also indicate your locale and keyboard settings.

**Comment by FillyAgioro** [comment]
Thanks You so It really worked 😇️
