### ISSUE TITLE
Black screen after suspending

### ISSUE THREAD

**Issue by tomaswarynyca** [elementary/settings-daemon#26]
## What Happened
Displays black screen after suspending, only the cursor appears.

## Steps to Reproduce

1. Suspend the machine
2. Pressing space to un-suspend the machine
3. The desktop remains black, only the cursor appears.

## Platform Information
Elementary OS 6 Early Access
Linux 5.8.0-48-generic

**Comment by cassidyjames** [comment]
@tomaswarynyca could you provide some hardware details? Specifically, are you on an NVIDIA graphics?

**Comment by tomaswarynyca** [comment]
Uhh sorry I forgot that detail, my notebook is ASUS-X512DA
- AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx @ 8x 2,1GHz

**Comment by tomaswarynyca** [comment]
I bring news about the case, a few days ago after an update of kernel and xorg by ubuntu the problem was solved. 

The problem now is with the automatic suspension :/
When you want to resume everything appears in black and only the cursor is seen.
