### ISSUE TITLE
Housekeeping keeps deleting my home directory

### ISSUE THREAD

**Issue by GammaGames** [elementary/settings-daemon#49]
### What Happened?

For the third time in as many weeks, I reboot my computer after lunch and my wallpaper is black, dock is empty, and chrome is no longer my default browser. Not much issue; I learned to take backups after the first time this happened and I lost several hours of work.

After restoring from backup, I open my terminal and run `systemd-tmpfiles --user --cat-config`:

```config
e "/home/jlieberg" - - - 7d
```

That's bad! 

### Steps to Reproduce

![Peek 2022-02-01 15-34](https://user-images.githubusercontent.com/7832163/152069984-f25c5bec-9d00-472f-8117-f2426d488d49.gif)

### Expected Behavior

I went into the code and found that the settings comes from [`GLib.UserDirectory.DOWNLOAD`](https://github.com/elementary/settings-daemon/blob/master/src/Backends/Housekeeping.vala#L117). It should probably warn the user if their download folder isn't set up correctly, I don't even know where to change that, so I'm not sure why mine keeps randomly resetting itself.

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

**Comment by davidmhewitt** [comment]
That is indeed bad!

At the very least, we should perform some sanity checks that the path returned from `GLib.UserDirectory.DOWNLOAD` is not your home directory. But it would be useful to figure out why this has happened.

I believe the setting for the location of the downloads folder should be in `~/.config/user-dirs.dirs` and there should be a `XDG_DOWNLOAD_DIR` key. Could you show the contents of that? Although, I guess, that file may not exist anymore if your home folder has been emptied :sweat: 

Do you have your system localised to another language, or have you ever done so in the past?

**Comment by GammaGames** [comment]
I had the file in my backup!

```bash
XDG_DESKTOP_DIR="$HOME/Desktop"
XDG_DOWNLOAD_DIR="$HOME/"
XDG_TEMPLATES_DIR="$HOME/"
XDG_PUBLICSHARE_DIR="$HOME/"
XDG_DOCUMENTS_DIR="$HOME/Documents"
XDG_MUSIC_DIR="$HOME/"
XDG_PICTURES_DIR="$HOME/Pictures"
XDG_VIDEOS_DIR="$HOME/"
```

Not localized, really no idea how it got set. Thanks for the quick fix!
