### ISSUE TITLE
Takeover DPMS helper

### ISSUE THREAD

**Issue by danrabbit** [elementary/settings-daemon#5]
https://github.com/elementary/dpms-helper

Called here: https://github.com/elementary/switchboard-plug-power/blob/master/src/MainView.vala#L318

**Comment by davidmhewitt** [comment]
I’m reasonably sure that it’s not even active/needed on focal anymore. Especially now that we’ve dropped light locker.

Would need to double check. But worth noting.

**Comment by danrabbit** [comment]
Seems like this is no longer necessary
